[tools]
bun = "latest"
go = "latest"
hyperfine = "latest"

[tasks.bench]
run = [
    "cd bun && bun install && bun run build",
    "cd go && go build",
    "cd .. && zig build benchmark",
    "bun run run.ts",
]
description = "Build all benchmarks and compare them with hyperfine"

[tasks.others]
run = [
    "cd bun && bun install && bun run build",
    "cd go && go build",
    "bun run run-others.ts",
]
description = "Build other libs and generate graphql"

[tasks.micro-bench]
run = ["cd .. && zig build micro-benchmark", "bun run run-micro-bench.ts"]
description = "Run micro benchmarks"
